<a href="https://colab.research.google.com/github/sindhuparusha225/Gen-AI-2025/blob/main/2303A52207_Week_08_Assignment_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. (1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library
2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.
3. (1 ponto) Build the application by loading the saved ANN model.
           Tabela 1: ANN Architecture
        Layer              Neurons   Activation Function
        Hidden Layer - 1     16      relu
        Hidden Layer - 2     20      relu
        Hidden Layer - 3     25      relu
        Hidden Layer - 4     10      relu
           Tabela 2: Training Parameters
        epochs   batch size   error metric   Optimizer
        100       64           accuracy      adadelta
Dataset: https://drive.google.com/file/d/1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO/view?
usp=drive_link

• Expected learning Outcomes from this assignment related to python

– Students are able to build ANN model with python deep learning libraries

– Students are able to deploy trained ANN model

– Students are able to measure training and testing performance of trained model

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset (replace with actual path after downloading manually)
dataset_path = "/content/winequality-red.csv"  # Modify as per actual filename
df = pd.read_csv(dataset_path)

# Convert categorical features to numeric using one-hot encoding (if applicable)
df = pd.get_dummies(df, drop_first=True)

# Assuming last column is target and rest are features
X = df.iloc[:, :-1].values  # Features
y = df.iloc[:, -1].values   # Target (classification)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define ANN model
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

# Save the model
model.save("wine_quality_model.h5")

# Load the saved model for deployment
loaded_model = keras.models.load_model("wine_quality_model.h5")

# Evaluate performance
y_train_pred = (model.predict(X_train) > 0.5).astype(int)
y_test_pred = (model.predict(X_test) > 0.5).astype(int)

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
class_report = classification_report(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy}")
print(f"Testing Accuracy: {test_accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

# Deploy: Predict wine quality for a new input (example)
def predict_wine_quality(input_features):
    input_scaled = scaler.transform([input_features])
    prediction = loaded_model.predict(input_scaled)
    return "Good Quality" if prediction[0][0] > 0.5 else "Poor Quality"

# Example usage
new_sample = X_test[0]  # Example test data
predicted_quality = predict_wine_quality(new_sample)
print(f"Predicted Wine Quality: {predicted_quality}")


Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.0000e+00 - loss: -2.2209 - val_accuracy: 0.0000e+00 - val_loss: -2.3307
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: -2.2889 - val_accuracy: 0.0000e+00 - val_loss: -2.3363
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: -2.1179 - val_accuracy: 0.0000e+00 - val_loss: -2.3419
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -2.2546 - val_accuracy: 0.0000e+00 - val_loss: -2.3476
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -2.3066 - val_accuracy: 0.0000e+00 - val_loss: -2.3535
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -2.2372 - val_accuracy: 0.0000e+00 - val_loss: -2.3594
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -2.3049 - val_accuracy: 0.0000e+00 - val_loss: -2.3655
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step -

40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Training Accuracy: 0.0
Testing Accuracy: 0.0
Confusion Matrix:
[[  0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0]
 [130   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      0.00      0.00     320.0

1/1 ━━━━━━━━━━━━━━━━

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

Predicted Wine Quality: Good Quality
