<a href="https://colab.research.google.com/github/sindhuparusha225/Gen-AI-2025/blob/main/2303A52207_Week_08_Assignment_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. (1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library

2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.

3. (1 ponto) Build the application by loading the saved ANN model.

          Tabela 1: ANN Architecture
        Layer             Neurons   Activation Function
        Hidden Layer - 1  12          tanh
        Hidden Layer - 2  24          tanh
        Hidden Layer - 3  30          tanh
        Hidden Layer - 4  20          tanh
        Hidden Layer - 5  10          tanh
          Tabela 2: Training Parameters
        epochs  batch size  error metric  Optimizer
        200      32          accuracy      adam
Dataset: https://drive.google.com/file/d/1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO/view?
usp=drive_link

• Expected learning Outcomes from this assignment related to python

– Students are able to build ANN model with python deep learning libraries

– Students are able to deploy trained ANN model

– Students are able to measure training and testing performance of trained model

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset (replace with actual path after downloading manually)
dataset_path = "/content/winequality-red.csv"  # Modify as per actual filename
df = pd.read_csv(dataset_path)

# Convert categorical features to numeric using one-hot encoding (if applicable)
df = pd.get_dummies(df, drop_first=True)

# Assuming last column is target and rest are features
X = df.iloc[:, :-1].values  # Features
y = df.iloc[:, -1].values   # Target (classification)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define ANN model
model = Sequential([
    Dense(12, activation='tanh', input_shape=(X_train.shape[1],)),
    Dense(24, activation='tanh'),
    Dense(30, activation='tanh'),
    Dense(20, activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(X_test, y_test))

# Save the model
model.save("wine_quality_model.h5")

# Load the saved model for deployment
loaded_model = keras.models.load_model("wine_quality_model.h5")

# Evaluate performance
y_train_pred = (model.predict(X_train) > 0.5).astype(int)
y_test_pred = (model.predict(X_test) > 0.5).astype(int)

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
class_report = classification_report(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy}")
print(f"Testing Accuracy: {test_accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

# Deploy: Predict wine quality for a new input (example)
def predict_wine_quality(input_features):
    input_scaled = scaler.transform([input_features])
    prediction = loaded_model.predict(input_scaled)
    return "Good Quality" if prediction[0][0] > 0.5 else "Poor Quality"

# Example usage
new_sample = X_test[0]  # Example test data
predicted_quality = predict_wine_quality(new_sample)
print(f"Predicted Wine Quality: {predicted_quality}")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.0000e+00 - loss: -0.6769 - val_accuracy: 0.0000e+00 - val_loss: -6.8201
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -9.3698 - val_accuracy: 0.0000e+00 - val_loss: -16.6623
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -18.1045 - val_accuracy: 0.0000e+00 - val_loss: -21.6811
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -22.2579 - val_accuracy: 0.0000e+00 - val_loss: -24.8469
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -25.2849 - val_accuracy: 0.0000e+00 - val_loss: -27.5291
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -27.8949 - val_accuracy: 0.0000e+00 - val_loss: -30.0221
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -30.1718 - val_accuracy: 0.0000e+00 - val_loss: -32.4160
Epoch 8/200
40/40 ━━━━━━━━━━━━

40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
Training Accuracy: 0.0
Testing Accuracy: 0.0
Confusion Matrix:
[[  0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0]
 [130   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      0.00      0.00     320.0



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
Predicted Wine Quality: Good Quality
