<a href="https://colab.research.google.com/github/sindhuparusha225/Gen-AI-2025/blob/main/Gen_AI_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write Python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with the outcomes of libraries?



  YActual    _    YP red


20    _   20.5


30    _   30.3


40    _   40.2


50   _    50.6


60     _  60.7


Tabela 1: YActual Vs. YP red

In [ ]:
 import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
YActual_reg = np.array([20, 30, 40, 50, 60])
YPred_reg = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

In [ ]:
mae = np.mean(np.abs(YActual_reg - YPred_reg))
mse = np.mean((YActual_reg - YPred_reg) ** 2)
rmse = np.sqrt(mse)
r2 = r2_score(YActual_reg, YPred_reg)

In [ ]:
print("Regression Metrics:")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

Regression Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R²): 0.99877


In [ ]:
print("\nLibrary-based Regression Metrics (from scikit-learn):")
print(f"MAE (sklearn): {mean_absolute_error(YActual_reg, YPred_reg)}")
print(f"MSE (sklearn): {mean_squared_error(YActual_reg, YPred_reg)}")
print(f"R² (sklearn): {r2_score(YActual_reg, YPred_reg)}")


Library-based Regression Metrics (from scikit-learn):
MAE (sklearn): 0.4600000000000016
MSE (sklearn): 0.24600000000000147
R² (sklearn): 0.99877


In [ ]:
YActual_class = np.array([0, 0, 1, 1, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 2])
YPred_class = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 0, 2, 1, 2, 2, 2])

In [ ]:
accuracy = accuracy_score(YActual_class, YPred_class)
precision = precision_score(YActual_class, YPred_class, average='macro', zero_division=0)
recall = recall_score(YActual_class, YPred_class, average='macro', zero_division=0)
f1 = f1_score(YActual_class, YPred_class, average='macro', zero_division=0)
conf_matrix = confusion_matrix(YActual_class, YPred_class)

In [ ]:
print("\nClassification Metrics:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")


Classification Metrics:
Accuracy: 0.8125
Precision: 0.8055555555555557
Recall: 0.8214285714285715
F1 Score: 0.8094405594405595
Confusion Matrix:
[[5 1 1]
 [1 3 0]
 [0 0 5]]


In [ ]:
print("\nLibrary-based Classification Metrics (from scikit-learn):")
print(f"Accuracy (sklearn): {accuracy_score(YActual_class, YPred_class)}")
print(f"Precision (sklearn): {precision_score(YActual_class, YPred_class, average='macro', zero_division=0)}")
print(f"Recall (sklearn): {recall_score(YActual_class, YPred_class, average='macro', zero_division=0)}")
print(f"F1 Score (sklearn): {f1_score(YActual_class, YPred_class, average='macro', zero_division=0)}")
print(f"Confusion Matrix (sklearn):\n{confusion_matrix(YActual_class, YPred_class)}")


Library-based Classification Metrics (from scikit-learn):
Accuracy (sklearn): 0.8125
Precision (sklearn): 0.8055555555555557
Recall (sklearn): 0.8214285714285715
F1 Score (sklearn): 0.8094405594405595
Confusion Matrix (sklearn):
[[5 1 1]
 [1 3 0]
 [0 0 5]]


2. Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries


YActual _ YP red


0 _ 0 _ 1 1 2 0


0 _ 0 _1 0 2 0


0 _ 1 _ 1 2 2 1


0 _ 2 _ 1 0 2 2


0 _  2  _ 1 2 2 2


Tabela 2: YActual Vs. YP red

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [ ]:
Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])

In [ ]:
n = len(Y_actual)

In [ ]:
true_positive = {0: 0, 1: 0, 2: 0}
false_positive = {0: 0, 1: 0, 2: 0}
false_negative = {0: 0, 1: 0, 2: 0}
true_negative = {0: 0, 1: 0, 2: 0}

In [ ]:
for i in range(n):
    for cls in [0, 1, 2]:
        if Y_actual[i] == cls and Y_pred[i] == cls:
            true_positive[cls] += 1
        elif Y_actual[i] != cls and Y_pred[i] == cls:
            false_positive[cls] += 1
        elif Y_actual[i] == cls and Y_pred[i] != cls:
            false_negative[cls] += 1
        elif Y_actual[i] != cls and Y_pred[i] != cls:
            true_negative[cls] += 1

In [ ]:
accuracy_scratch = sum([true_positive[cls] for cls in [0, 1, 2]]) / n

In [ ]:
precision_scratch = {cls: true_positive[cls] / (true_positive[cls] + false_positive[cls]) if (true_positive[cls] + false_positive[cls]) > 0 else 0 for cls in [0, 1, 2]}
recall_scratch = {cls: true_positive[cls] / (true_positive[cls] + false_negative[cls]) if (true_positive[cls] + false_negative[cls]) > 0 else 0 for cls in [0, 1, 2]}
f1_score_scratch = {cls: 2 * precision_scratch[cls] * recall_scratch[cls] / (precision_scratch[cls] + recall_scratch[cls]) if (precision_scratch[cls] + recall_scratch[cls]) > 0 else 0 for cls in [0, 1, 2]}


In [ ]:
print("Metrics calculated from scratch:")
print(f"Accuracy: {accuracy_scratch}")
for cls in [0, 1, 2]:
    print(f"Class {cls} - Precision: {precision_scratch[cls]}, Recall: {recall_scratch[cls]}, F1-Score: {f1_score_scratch[cls]}")

Metrics calculated from scratch:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7000000000000001
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [ ]:
accuracy_library = accuracy_score(Y_actual, Y_pred)
precision_library = precision_score(Y_actual, Y_pred, average=None)
recall_library = recall_score(Y_actual, Y_pred, average=None)
f1_library = f1_score(Y_actual, Y_pred, average=None)

In [ ]:
print("\nMetrics calculated using libraries:")
print(f"Accuracy: {accuracy_library}")
for cls, (p, r, f1) in enumerate(zip(precision_library, recall_library, f1_library)):
    print(f"Class {cls} - Precision: {p}, Recall: {r}, F1-Score: {f1}")


Metrics calculated using libraries:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [ ]:
print("\nDetailed Classification Report:")
print(classification_report(Y_actual, Y_pred))


Detailed Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

